### PR TITLE
Make it work with kodi 19.0_beta2

### PR DESCRIPTION
**Pull request by wrtlprnft**
The plugin fails to load with Kodi 19.0_beta2. After bumping the version of xbmc.python, I've had to fix some small issues to make it actually work.

Disclaimer: I don't have any experience with Kodi add-on development. No idea if what I changed makes any sense, but it works…

### CODE REVIEW

**Comment by Memphiz** [comment]
Thx for fixing it for matrix. But this PR needs to go to

https://github.com/xbmc/repo-scripts/tree/matrix

(Matrix branch)

**Comment by wrtlprnft** [comment]
Okay, so I guess I should bump the version number, too? Should I make any other changes to addon.xml?

**Comment by Memphiz** [comment]
Bump version for sure. I am out of loop for quiet a while now so I suggest you setup the pull request and ask for anything else there then.
Thx again for your patience.

**Comment by wrtlprnft** [comment]
The repo-scripts repo accepted a new version after I did some other minor changes on their request, so I'm closing this pull request.

On their request, I've changed the addon's official repository to my repository. I've also changed LICENSE.txt to the GPL 3 text because that's what is used in the copyright headers of the `.py` files.

Please let me know if/when you want to change something about this. I can only keep this plugin on “life support” (i. e. keep it working for me on whatever Kodi version I use). I was honestly surprised to see how many features it has.

**Pull request closed without merging**
